name: Upload translations to Transifex

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    # if PR with label `i18n` is merged
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'i18n')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install deps
        run: yarn
      - name: Upload translations
        run: node scripts/transifex.mjs push
        env:
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          DIFF_URL: ${{ github.event.pull_request.diff_url }}
